export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const SET_PATIENTS = "SET_PATIENTS";

export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

export const SET_PAGE = "SET_PAGE";

export const SUBMIT_PATIENT_FORM = "SUBMIT_PATIENT_FORM";
export const SUBMIT_PATIENT_SUCCESS = "SUBMIT_PATIENT_SUCCESS";

export const QUEUE_PATIENT_FORM = "QUEUE_PATIENT_FORM";
export const PROCESS_QUEUE = "PROCESS_QUEUE";

export const FETCH_PATIENT_DETAILS = "FETCH_PATIENT_DETAILS";
export const SET_PATIENT_DETAILS = "SET_PATIENT_DETAILS";

export const CLEAR_QUEUE = "CLEAR_QUEUE";
